# Generated by Django 5.2.4 on 2025-07-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('dream_date', models.DateField()),
                ('ai_interpretation', models.TextField(blank=True, null=True)),
                ('generated_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('entry_created_at', models.DateTimeField(auto_now_add=True)),
                ('persons', models.ManyToManyField(blank=True, to='somnologia_app.person')),
            ],
            options={
                'ordering': ['-dream_date', '-entry_created_at'],
            },
        ),
    ]
