# Generated by Django 5.2.4 on 2025-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somnologia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='dream',
            name='tags',
        ),
        migrations.AddField(
            model_name='dream',
            name='tags',
            field=models.ManyToManyField(blank=True, to='somnologia_app.tag'),
        ),
    ]
