# Generated by Django 5.2.4 on 2025-07-07 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somnologia_app', '0002_tag_remove_dream_tags_dream_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dream',
            options={'ordering': ['-dream_date', '-entry_created_at'], 'verbose_name': 'Dream', 'verbose_name_plural': 'Dreams'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description or role of the person in dreams, or notes about them.', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this person entry was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when this tag entry was created.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dream',
            name='ai_interpretation',
            field=models.TextField(blank=True, help_text='AI-generated interpretation of the dream.', null=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='description',
            field=models.TextField(help_text='The detailed description of the dream.'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dream_date',
            field=models.DateField(blank=True, help_text='The date on which the dream occurred (user input, can be approximate).', null=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this dream entry was created in the system.'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='generated_image_url',
            field=models.URLField(blank=True, help_text='URL to an AI-generated image representing the dream.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='persons',
            field=models.ManyToManyField(blank=True, help_text='Persons involved in or related to the dream.', related_name='dreams', to='somnologia_app.person'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Descriptive tags associated with the dream.', related_name='dreams', to='somnologia_app.tag'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='The name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional photo of the person.', null=True, upload_to='person_photos/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text="An optional longer description for the tag's meaning or common usage.", null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text="The name of the tag (e.g., 'Lucid', 'Nightmare').", max_length=100, unique=True),
        ),
    ]
